[tool.poetry]
name = "vss365-today"
version = "0.8.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^1.0"
flask-wtf = "^0.14.2"
python-dotenv = "^0.10"
tweepy = "^3.7"
mailjet_rest = "^1.3"
gunicorn = "^19.9"

[tool.poetry.dev-dependencies]
rope = "^0.14.0"
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
