[tool.poetry]
name = "vss365today"
version = "1.0.0"
description = "#vss365 today website"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^1.1.2"
flask-wtf = "^0.14.3"
gunicorn = "^20.0.4"
requests = "^2.25.1"
email-validator = "^1.1.2"
WTForms-Components = "^0.10.4"
flask-google-fonts = {url = "https://github.com/le717/flask-google-fonts/releases/download/v1.0.0/flask_google_fonts-1.0.0-py3-none-any.whl"}
sys-vars = "^4.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
mypy = "^0.790"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
