[tool.poetry]
name = "vss365-today"
version = "1.0.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1"
flask-wtf = "^0.14.3"
tweepy = "^3.8"
gunicorn = "^20.0"
requests = "^2.23"
pyjwt = "^1.7.1"
sys-vars = {url = "https://github.com/le717/sys-vars/releases/download/v1.0.0/sys_vars-1.0.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
rope = "^0.16.0"
flake8 = "^3.7"
mypy = "^0.770"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
