[tool.poetry]
name = "vss365-today"
version = "1.0.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1"
flask-wtf = "^0.14.2"
python-dotenv = "^0.10"
tweepy = "^3.8"
mailjet_rest = "^1.3"
gunicorn = "^19.9"
requests = "^2.22"
flask-jwt-extended = "^3.24.1"

[tool.poetry.dev-dependencies]
rope = "^0.14.0"
flake8 = "^3.7"
mypy = "^0.740"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
