[tool.poetry]
name = "vss365"
version = "0.4.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.0"
flask-wtf = "^0.14.2"
python-dotenv = "^0.10.1"
tweepy = "^3.7"
Flask-SQLAlchemy = "^2.3"
pymysql = "^0.9.3"
mailjet_rest = "^1.3"

[tool.poetry.dev-dependencies]
rope = "^0.11.0"
flake8 = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
